import random
import string
from dataclasses import dataclass, field


def generate_id() -> str:
    """
    Generates a random string of 15 chars to be a unique ID.

    Returns:
        str: A random string of 15 lowercase letters.
    """
    return "".join(random.choices(string.ascii_lowercase, k=15))


@dataclass
class Student:
    """
    A dataclass representing a student,
    with fields for name, surname, active status,
    login, and a randomly generated ID.

    Attributes:
        name (str): First name of the student. Passed during instantiation.
        surname (str): Surname of the student. Passed during instantiation.
        active (bool): Whether the student is active or not.
        login (str): The login name generated from the name and surname.
        id (str): A randomly generated unique ID for the student.
    """
    name: str = field(init=True)
    surname: str = field(init=True)
    active: bool = field(default=True, init=False)
    login: str = field(init=False)
    id: str = field(default_factory=generate_id, init=False)

    def __post_init__(self):
        """
        Post-initialization method to set the `login` field after the instance
        has been initialized by the dataclass.

        The login is generated by combining the first letter of the name
        (capitalized) with the entire surname in lowercase.

        For example, if the student's
        name is "John" and surname is "DOE", the login will be "Jdoe".
        """
        self.login = self.name[0].capitalize() + self.surname.lower()
